plugins:
  knowledge_explorer_enabled:
    default: false
    client: true
  knowledge_explorer_categories:
    type: category_list
    default: ""
    client: true
  knowledge_explorer_tags:
    type: list
    default: ""
    client: true
