plugins:
  resources_enabled:
    default: false
    client: true
  resources_categories:
    type: category_list
    default: ""
    client: true
  resources_tags:
    type: tag_list
    default: ""
    client: true
  resources_add_solved_filter:
    default: false
    client: true
  resources_add_to_top_menu:
    default: false
    client: true
